# Generated by Django 4.2.16 on 2025-10-26 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification')], max_length=20)),
                ('recipient', models.CharField(help_text='Email address, phone number, or user ID', max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='queued', max_length=20)),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('metadata', models.JSONField(default=dict, help_text='Campaign ID, Deal ID, User ID, etc.')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communication_logs',
                'indexes': [models.Index(fields=['message_type'], name='communicati_message_3e099c_idx'), models.Index(fields=['status'], name='communicati_status_10f02f_idx'), models.Index(fields=['recipient'], name='communicati_recipie_b2021b_idx'), models.Index(fields=['message_id'], name='communicati_message_bfc846_idx'), models.Index(fields=['created_at'], name='communicati_created_b71929_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verification_tokens',
                'indexes': [models.Index(fields=['token_hash'], name='email_verif_token_h_af9b84_idx'), models.Index(fields=['user'], name='email_verif_user_id_bef55e_idx'), models.Index(fields=['expires_at'], name='email_verif_expires_770728_idx')],
            },
        ),
    ]
