# Generated by Django 4.2.16 on 2025-11-22 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phone_verification_tokens',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(help_text='Type of message: verification, forgot_password, invitation, etc.', max_length=50)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count_hour', models.IntegerField(default=0, help_text='Messages sent in the last hour')),
                ('sent_count_minute', models.IntegerField(default=0, help_text='Messages sent in the last minute')),
                ('hour_window_start', models.DateTimeField(blank=True, null=True)),
                ('minute_window_start', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'whatsapp_rate_limits',
            },
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='country_code',
            field=models.CharField(blank=True, help_text='Country code (e.g., +91, +1)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number without country code', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='sender_id',
            field=models.IntegerField(blank=True, help_text='ID of the brand or influencer who sent the message', null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='sender_type',
            field=models.CharField(blank=True, choices=[('brand', 'Brand'), ('influencer', 'Influencer'), ('system', 'System')], help_text='Type of sender (brand, influencer, or system)', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['sender_type', 'sender_id'], name='communicati_sender__2f062c_idx'),
        ),
        migrations.AddField(
            model_name='whatsappratelimit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_rate_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phoneverificationtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='whatsappratelimit',
            index=models.Index(fields=['user', 'message_type'], name='whatsapp_ra_user_id_c9933f_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappratelimit',
            index=models.Index(fields=['last_sent_at'], name='whatsapp_ra_last_se_2d1bc0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappratelimit',
            unique_together={('user', 'message_type')},
        ),
        migrations.AddIndex(
            model_name='phoneverificationtoken',
            index=models.Index(fields=['token_hash'], name='phone_verif_token_h_22cc19_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverificationtoken',
            index=models.Index(fields=['user'], name='phone_verif_user_id_2011c6_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverificationtoken',
            index=models.Index(fields=['expires_at'], name='phone_verif_expires_587751_idx'),
        ),
    ]
