# Generated by Django 4.2.16 on 2025-12-01 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0002_phoneverificationtoken_whatsappratelimit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(db_index=True, max_length=64)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], help_text='Channel through which OTP was sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_otps',
                'indexes': [models.Index(fields=['otp_hash'], name='password_re_otp_has_48728d_idx'), models.Index(fields=['user'], name='password_re_user_id_4d8cfa_idx'), models.Index(fields=['expires_at'], name='password_re_expires_be232c_idx'), models.Index(fields=['created_at'], name='password_re_created_cc59d5_idx')],
            },
        ),
    ]
