# Generated by Django 4.2.16 on 2025-12-03 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(db_index=True, max_length=64)),
                ('phone_number', models.CharField(help_text='Phone number without country code', max_length=15)),
                ('country_code', models.CharField(help_text='Country code (e.g., +91, +1)', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'phone_verification_otps',
                'indexes': [models.Index(fields=['otp_hash'], name='phone_verif_otp_has_08b685_idx'), models.Index(fields=['user'], name='phone_verif_user_id_9014a2_idx'), models.Index(fields=['expires_at'], name='phone_verif_expires_27d0d8_idx')],
            },
        ),
    ]
