# Generated by Django 4.2.16 on 2026-01-03 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_target_influencer_genders_and_more'),
        ('influencers', '0019_delete_celerytask'),
        ('communications', '0004_phoneverificationotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTemplateMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('invitation', 'Invitation'), ('status_update', 'Status Update'), ('accepted', 'Accepted'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('verification', 'Verification'), ('otp', 'OTP')], max_length=40)),
                ('param_mapping', models.JSONField(blank=True, default=dict)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_fallback_enabled', models.BooleanField(default=False)),
                ('sms_fallback_timeout_seconds', models.IntegerField(default=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaign_template_mappings',
            },
        ),
        migrations.CreateModel(
            name='InfluencerMessageOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('invitation', 'Invitation'), ('status_update', 'Status Update'), ('accepted', 'Accepted'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('verification', 'Verification'), ('otp', 'OTP')], max_length=40)),
                ('param_mapping_override', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'influencer_message_overrides',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(db_index=True, max_length=80)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20)),
                ('provider', models.CharField(default='msg91', max_length=50)),
                ('provider_template_name', models.CharField(help_text='Template name on provider', max_length=200)),
                ('provider_template_id', models.CharField(blank=True, default='', help_text='Template id on provider', max_length=200)),
                ('language_code', models.CharField(blank=True, default='en', max_length=20)),
                ('params_schema', models.JSONField(blank=True, default=list)),
                ('raw_provider_payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default for (template_key + channel)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'message_templates',
                'permissions': [('communication_admin', 'Can manage communications (templates, bulk send, analytics)')],
            },
        ),
        migrations.CreateModel(
            name='MSG91SenderNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for ops/admin users', max_length=120)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=32)),
                ('sms_sender_id', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Provider specific config (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'msg91_sender_numbers',
            },
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='provider',
            field=models.CharField(blank=True, default='', help_text='Upstream provider (e.g., msg91, meta)', max_length=50),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Provider message identifier used in webhooks (if available)', max_length=255),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('undelivered', 'Undelivered'), ('rejected', 'Rejected'), ('retrying', 'Retrying')], default='queued', max_length=20),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['provider', 'provider_message_id'], name='communicati_provide_604ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='msg91sendernumber',
            index=models.Index(fields=['channel', 'is_active'], name='msg91_sende_channel_2a4f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='msg91sendernumber',
            index=models.Index(fields=['channel', 'is_default'], name='msg91_sende_channel_d8008c_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['template_key', 'channel'], name='message_tem_templat_07ce7b_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['provider', 'provider_template_name'], name='message_tem_provide_e42210_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['is_active'], name='message_tem_is_acti_f419d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together={('template_key', 'channel', 'provider', 'provider_template_name')},
        ),
        migrations.AddField(
            model_name='influencermessageoverride',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_overrides', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='influencermessageoverride',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_overrides', to='influencers.influencerprofile'),
        ),
        migrations.AddField(
            model_name='influencermessageoverride',
            name='sms_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'channel': 'sms'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencer_sms_overrides', to='communications.messagetemplate'),
        ),
        migrations.AddField(
            model_name='influencermessageoverride',
            name='whatsapp_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'channel': 'whatsapp'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencer_whatsapp_overrides', to='communications.messagetemplate'),
        ),
        migrations.AddField(
            model_name='campaigntemplatemapping',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_mappings', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaigntemplatemapping',
            name='sender_number',
            field=models.ForeignKey(blank=True, help_text='Optional sender override for this campaign (otherwise default sender is used)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_mappings', to='communications.msg91sendernumber'),
        ),
        migrations.AddField(
            model_name='campaigntemplatemapping',
            name='sms_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'channel': 'sms'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_sms_mappings', to='communications.messagetemplate'),
        ),
        migrations.AddField(
            model_name='campaigntemplatemapping',
            name='whatsapp_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'channel': 'whatsapp'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_whatsapp_mappings', to='communications.messagetemplate'),
        ),
        migrations.AddIndex(
            model_name='influencermessageoverride',
            index=models.Index(fields=['campaign', 'notification_type'], name='influencer__campaig_eabd61_idx'),
        ),
        migrations.AddIndex(
            model_name='influencermessageoverride',
            index=models.Index(fields=['influencer'], name='influencer__influen_0398a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='influencermessageoverride',
            unique_together={('campaign', 'influencer', 'notification_type')},
        ),
        migrations.AddIndex(
            model_name='campaigntemplatemapping',
            index=models.Index(fields=['campaign', 'notification_type'], name='campaign_te_campaig_b0793d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntemplatemapping',
            index=models.Index(fields=['is_active'], name='campaign_te_is_acti_a5bb24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigntemplatemapping',
            unique_together={('campaign', 'notification_type')},
        ),
    ]
