# Generated by Cursor on 2026-01-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_campaigntemplatemapping_influencermessageoverride_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='provider_integrated_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together={('template_key', 'channel', 'provider', 'provider_integrated_number', 'provider_template_name')},
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['provider_integrated_number'], name='message_tem_provider_int_2cf7dd_idx'),
        ),
    ]


