# Generated by Django 4.2.16 on 2026-01-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_messagetemplate_provider_integrated_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='messagetemplate',
            name='message_tem_provider_int_2cf7dd_idx',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='provider_namespace',
            field=models.CharField(blank=True, default='', help_text='MSG91 WhatsApp namespace (required for bulk API)', max_length=255),
        ),
    ]
