# Generated by Django 4.2.16 on 2025-09-03 21:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('shortlisted', 'Shortlisted'), ('address_requested', 'Address Requested'), ('address_provided', 'Address Provided'), ('product_shipped', 'Product Shipped'), ('product_delivered', 'Product Delivered'), ('active', 'Active'), ('content_submitted', 'Content Submitted'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('dispute', 'Dispute')], default='invited', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('negotiation_notes', models.TextField(blank=True)),
                ('custom_terms_agreed', models.TextField(blank=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('brand_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('brand_review', models.TextField(blank=True)),
                ('influencer_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('influencer_review', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Brand notes about this deal')),
                ('shipping_address', models.JSONField(blank=True, help_text='Shipping address for barter deals', null=True)),
                ('tracking_number', models.CharField(blank=True, help_text='Tracking number for shipped products', max_length=100)),
                ('tracking_url', models.URLField(blank=True, help_text='Tracking URL for shipped products')),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('address_requested_at', models.DateTimeField(blank=True, null=True)),
                ('address_provided_at', models.DateTimeField(blank=True, null=True)),
                ('shortlisted_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'deals',
            },
        ),
    ]
