# Generated by Django 4.2.16 on 2025-01-08 00:00
# Migration for moving Deal model from core to deals app

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('active', 'Active'), ('content_submitted', 'Content Submitted'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='invited', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('negotiation_notes', models.TextField(blank=True)),
                ('custom_terms_agreed', models.TextField(blank=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('brand_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('brand_review', models.TextField(blank=True)),
                ('influencer_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('influencer_review', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='campaigns.campaign')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='influencers.influencerprofile')),
            ],
            options={
                'db_table': 'deals',
                'indexes': [models.Index(fields=['status'], name='deals_status_idx'), models.Index(fields=['payment_status'], name='deals_payment_status_idx'), models.Index(fields=['invited_at'], name='deals_invited_at_idx'), models.Index(fields=['completed_at'], name='deals_completed_at_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('campaign', 'influencer')},
        ),
    ]