# Generated by Django 4.2.16 on 2025-09-03 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('influencers', '0001_initial'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='influencers.influencerprofile'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['status'], name='deals_status_eeb583_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['payment_status'], name='deals_payment_3dc664_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['invited_at'], name='deals_invited_0de380_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['completed_at'], name='deals_complet_63ee5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('campaign', 'influencer')},
        ),
    ]
