# Generated by Django 4.2.16 on 2025-08-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_status_eeb583_idx',
            old_name='deals_status_idx',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_payment_3dc664_idx',
            old_name='deals_payment_status_idx',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_invited_0de380_idx',
            old_name='deals_invited_at_idx',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_complet_63ee5f_idx',
            old_name='deals_completed_at_idx',
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('active', 'Active'), ('content_submitted', 'Content Submitted'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('dispute', 'Dispute')], default='invited', max_length=20),
        ),
    ]
