# Generated by Django 4.2.16 on 2025-08-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_rename_deals_status_idx_deals_status_eeb583_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='address_provided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='address_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='shipping_address',
            field=models.JSONField(blank=True, help_text='Shipping address for barter deals', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='shortlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Tracking number for shipped products', max_length=100),
        ),
        migrations.AddField(
            model_name='deal',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='Tracking URL for shipped products'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('shortlisted', 'Shortlisted'), ('address_requested', 'Address Requested'), ('address_provided', 'Address Provided'), ('product_shipped', 'Product Shipped'), ('product_delivered', 'Product Delivered'), ('active', 'Active'), ('content_submitted', 'Content Submitted'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('dispute', 'Dispute')], default='invited', max_length=20),
        ),
    ]
