# Generated by Django 4.2.16 on 2025-12-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='tracking_url',
            field=models.TextField(blank=True, default='', help_text='Tracking URL for shipped products'),
        ),
    ]
