# Generated by Django 4.2.16 on 2025-08-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_deal_address_provided_at_deal_address_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='notes',
            field=models.TextField(blank=True, help_text='Brand notes about this deal'),
        ),
    ]
