# Generated by Django 4.2.16 on 2025-09-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('request_revision', 'Revision Requested')], max_length=20)),
                ('feedback', models.TextField(blank=True, help_text='Review feedback from brand')),
                ('revision_notes', models.TextField(blank=True, help_text='Specific revision instructions')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content_review_history',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest')], max_length=20)),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('story', 'Story'), ('reel', 'Reel'), ('post', 'Post')], max_length=20)),
                ('file_url', models.URLField(blank=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='content_submissions/')),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('mention_brand', models.BooleanField(default=True)),
                ('post_url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, help_text='Title or description of this content piece', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the content')),
                ('additional_links', models.JSONField(blank=True, help_text='Additional links with descriptions in format: [{"url": "...", "description": "..."}]', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_revision_update', models.DateTimeField(blank=True, help_text='When content was last updated after a revision request', null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('revision_requested', models.BooleanField(default=False)),
                ('revision_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0, help_text='Number of times this submission has been reviewed')),
            ],
            options={
                'db_table': 'content_submissions',
            },
        ),
    ]
