# Generated by Django 4.2.16 on 2025-08-04 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0002_rename_deals_status_idx_deals_status_eeb583_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest')], max_length=20)),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('story', 'Story'), ('reel', 'Reel'), ('post', 'Post')], max_length=20)),
                ('file_url', models.URLField(blank=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='content_submissions/')),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('mention_brand', models.BooleanField(default=True)),
                ('post_url', models.URLField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('revision_requested', models.BooleanField(default=False)),
                ('revision_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_submissions', to='deals.deal')),
            ],
            options={
                'db_table': 'content_submissions',
                'indexes': [models.Index(fields=['deal'], name='content_sub_deal_id_b79430_idx'), models.Index(fields=['platform'], name='content_sub_platfor_d73e23_idx'), models.Index(fields=['content_type'], name='content_sub_content_609e9c_idx'), models.Index(fields=['submitted_at'], name='content_sub_submitt_441e0f_idx'), models.Index(fields=['approved'], name='content_sub_approve_ab5a6a_idx')],
            },
        ),
    ]
