# Generated by Django 4.2.16 on 2025-09-03 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsubmission',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_submissions', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='contentsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Brand user who reviewed this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentreviewhistory',
            name='content_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='content.contentsubmission'),
        ),
        migrations.AddField(
            model_name='contentreviewhistory',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_review_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contentsubmission',
            index=models.Index(fields=['deal'], name='content_sub_deal_id_b79430_idx'),
        ),
        migrations.AddIndex(
            model_name='contentsubmission',
            index=models.Index(fields=['platform'], name='content_sub_platfor_d73e23_idx'),
        ),
        migrations.AddIndex(
            model_name='contentsubmission',
            index=models.Index(fields=['content_type'], name='content_sub_content_609e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='contentsubmission',
            index=models.Index(fields=['submitted_at'], name='content_sub_submitt_441e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='contentsubmission',
            index=models.Index(fields=['approved'], name='content_sub_approve_ab5a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreviewhistory',
            index=models.Index(fields=['content_submission'], name='content_rev_content_adb688_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreviewhistory',
            index=models.Index(fields=['reviewed_at'], name='content_rev_reviewe_c9d487_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreviewhistory',
            index=models.Index(fields=['action'], name='content_rev_action_68ae63_idx'),
        ),
    ]
