# Generated by Django 4.2.16 on 2025-08-29 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsubmission',
            name='additional_links',
            field=models.JSONField(blank=True, help_text='Additional links with descriptions in format: [{"url": "...", "description": "..."}]', null=True),
        ),
        migrations.AddField(
            model_name='contentsubmission',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the content'),
        ),
        migrations.AddField(
            model_name='contentsubmission',
            name='review_count',
            field=models.IntegerField(default=0, help_text='Number of times this submission has been reviewed'),
        ),
        migrations.AddField(
            model_name='contentsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Brand user who reviewed this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentsubmission',
            name='title',
            field=models.CharField(blank=True, help_text='Title or description of this content piece', max_length=255),
        ),
    ]
