# Generated by Django 4.2.16 on 2025-08-29 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_contentsubmission_additional_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsubmission',
            name='last_revision_update',
            field=models.DateTimeField(blank=True, help_text='When content was last updated after a revision request', null=True),
        ),
        migrations.AddField(
            model_name='contentsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ContentReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('request_revision', 'Revision Requested')], max_length=20)),
                ('feedback', models.TextField(blank=True, help_text='Review feedback from brand')),
                ('revision_notes', models.TextField(blank=True, help_text='Specific revision instructions')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('content_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='content.contentsubmission')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_review_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_review_history',
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['content_submission'], name='content_rev_content_adb688_idx'), models.Index(fields=['reviewed_at'], name='content_rev_reviewe_c9d487_idx'), models.Index(fields=['action'], name='content_rev_action_68ae63_idx')],
            },
        ),
    ]
