# Generated by Django 4.2.16 on 2025-12-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_contentsubmission_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsubmission',
            name='file_url',
            field=models.TextField(blank=True, default='', help_text='URL to the uploaded file'),
        ),
        migrations.AlterField(
            model_name='contentsubmission',
            name='post_url',
            field=models.TextField(blank=True, default='', help_text='URL to the published post on social media'),
        ),
    ]
