# Generated by Django 4.2.16 on 2025-08-03 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectives', models.TextField(blank=True)),
                ('deal_type', models.CharField(choices=[('paid', 'Paid'), ('barter', 'Barter'), ('hybrid', 'Hybrid')], max_length=20)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('product_description', models.TextField(blank=True)),
                ('product_images', models.JSONField(blank=True, default=list)),
                ('product_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('available_sizes', models.JSONField(blank=True, default=list)),
                ('available_colors', models.JSONField(blank=True, default=list)),
                ('content_requirements', models.JSONField(blank=True, default=dict)),
                ('platforms_required', models.JSONField(blank=True, default=list)),
                ('content_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('special_instructions', models.TextField(blank=True)),
                ('application_deadline', models.DateTimeField()),
                ('product_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('content_creation_start', models.DateTimeField(blank=True, null=True)),
                ('content_creation_end', models.DateTimeField(blank=True, null=True)),
                ('submission_deadline', models.DateTimeField()),
                ('campaign_start_date', models.DateTimeField()),
                ('campaign_end_date', models.DateTimeField()),
                ('payment_schedule', models.TextField(blank=True)),
                ('shipping_details', models.TextField(blank=True)),
                ('custom_terms', models.TextField(blank=True)),
                ('allows_negotiation', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='brands.brand')),
            ],
            options={
                'db_table': 'campaigns',
                'indexes': [models.Index(fields=['brand'], name='campaigns_brand_i_c2d4bd_idx'), models.Index(fields=['deal_type'], name='campaigns_deal_ty_a41164_idx'), models.Index(fields=['application_deadline'], name='campaigns_applica_b78630_idx'), models.Index(fields=['campaign_start_date'], name='campaigns_campaig_ae7bbc_idx'), models.Index(fields=['is_active'], name='campaigns_is_acti_6c57d0_idx'), models.Index(fields=['created_at'], name='campaigns_created_9201e5_idx')],
            },
        ),
    ]
