# Generated by Django 4.2.16 on 2025-09-03 21:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectives', models.TextField(blank=True)),
                ('deal_type', models.CharField(choices=[('cash', 'Cash Payment'), ('product', 'Barter Only'), ('hybrid', 'Cash + Barter')], max_length=20)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('product_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('products', models.JSONField(blank=True, default=list, help_text='List of product objects for barter campaigns')),
                ('content_requirements', models.JSONField(blank=True, default=dict)),
                ('platforms_required', models.JSONField(blank=True, default=list)),
                ('special_instructions', models.TextField(blank=True)),
                ('target_influencers', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('content_count', models.IntegerField(default=0, help_text='Number of content pieces expected')),
                ('industry', models.CharField(default='other', max_length=50)),
                ('execution_mode', models.CharField(choices=[('manual', 'Manual'), ('manual_managed', 'Manual + Managed by Us'), ('fully_managed', 'Managed by Us Fully')], default='manual', max_length=20)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('product_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('submission_deadline', models.DateTimeField(blank=True, null=True)),
                ('barter_submission_after_days', models.IntegerField(blank=True, help_text='For barter deals, days after product received to submit content', null=True)),
                ('campaign_live_date', models.DateTimeField(blank=True, null=True)),
                ('application_deadline_visible_to_influencers', models.BooleanField(default=True)),
                ('payment_schedule', models.TextField(blank=True)),
                ('shipping_details', models.TextField(blank=True)),
                ('custom_terms', models.TextField(blank=True)),
                ('allows_negotiation', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='brands.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('industry_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_industries', to='common.industry')),
            ],
            options={
                'db_table': 'campaigns',
                'indexes': [models.Index(fields=['brand'], name='campaigns_brand_i_c2d4bd_idx'), models.Index(fields=['created_by'], name='campaigns_created_a7f3be_idx'), models.Index(fields=['deal_type'], name='campaigns_deal_ty_a41164_idx'), models.Index(fields=['industry'], name='campaigns_industr_e81e4f_idx'), models.Index(fields=['application_deadline'], name='campaigns_applica_b78630_idx'), models.Index(fields=['campaign_live_date'], name='campaigns_campaig_064bfc_idx'), models.Index(fields=['is_active'], name='campaigns_is_acti_6c57d0_idx'), models.Index(fields=['created_at'], name='campaigns_created_9201e5_idx')],
            },
        ),
    ]
