# Generated by Django 4.2.16 on 2025-10-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content_categories',
            field=models.JSONField(blank=True, default=list, help_text='List of content category keys'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='industries',
            field=models.JSONField(blank=True, default=list, help_text='List of industry keys'),
        ),
    ]
