# Generated by Django 5.2.5 on 2025-08-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
