# Generated by Django 5.2.5 on 2025-08-19 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_bookmarkedinfluencer_brandauditlog_branduser_and_more'),
        ('campaigns', '0002_alter_campaign_application_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['created_by'], name='campaigns_created_a7f3be_idx'),
        ),
    ]
