# Generated by Django 4.2.16 on 2025-10-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_content_categories_campaign_industries'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='target_influencer_age_ranges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_influencer_collaboration_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_influencer_max_collab_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
