# Generated by Django 4.2.16 on 2025-10-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_target_influencer_age_ranges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='target_influencer_genders',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_influencer_locations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
