# Generated by Django 4.2.16 on 2025-08-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='deal_type',
            field=models.CharField(choices=[('cash', 'Cash Payment'), ('product', 'Product Only'), ('hybrid', 'Cash + Product')], max_length=20),
        ),
    ]
