# Generated by Django 4.2.16 on 2025-08-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_deal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='product_quantity',
            new_name='target_influencers',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='available_sizes',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='product_images',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='product_name',
        ),
        migrations.AddField(
            model_name='campaign',
            name='application_deadline_visible_to_influencers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='barter_submission_after_days',
            field=models.IntegerField(blank=True, help_text='For barter deals, days after product received to submit content', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_live_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='List of category keys'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='execution_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('hybrid', 'Hybrid'), ('managed', 'Managed')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='products',
            field=models.JSONField(blank=True, default=list, help_text='List of product objects for barter campaigns'),
        ),
    ]
