# Generated by Django 4.2.16 on 2025-08-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('campaigns', '0005_rename_product_quantity_campaign_target_influencers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='categories',
        ),
        migrations.AddField(
            model_name='campaign',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Content categories for this campaign', related_name='campaigns', to='common.category'),
        ),
    ]
