# Generated by Django 4.2.16 on 2025-08-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_update_timeline_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaigns_campaig_ae7bbc_idx',
        ),
        migrations.AddField(
            model_name='campaign',
            name='content_count',
            field=models.IntegerField(default=0, help_text='Number of content pieces expected'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_live_date'], name='campaigns_campaig_064bfc_idx'),
        ),
    ]
