# Generated by Django 4.2.16 on 2025-08-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_industry_replace_categories'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaign',
            new_name='campaigns_industr_e81e4f_idx',
            old_name='campaigns_industry_idx',
        ),
    ]
