# Generated by Django 4.2.16 on 2025-08-26 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('campaigns', '0011_rename_campaigns_industry_idx_campaigns_industr_e81e4f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='industry_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_industries', to='common.category'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='industry',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
