# Generated by Django 4.2.16 on 2025-08-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_campaign_industry_category_alter_campaign_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='deal_type',
            field=models.CharField(choices=[('cash', 'Cash Payment'), ('product', 'Barter Only'), ('hybrid', 'Cash + Barter')], max_length=20),
        ),
    ]
