# Generated by Django 4.2.16 on 2025-09-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_alter_campaign_deal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='execution_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('manual_managed', 'Manual + Managed by Us'), ('fully_managed', 'Managed by Us Fully')], default='manual', max_length=20),
        ),
    ]
