# Generated by Django 4.2.16 on 2025-08-03 11:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('industry', models.CharField(choices=[('fashion_beauty', 'Fashion & Beauty'), ('food_lifestyle', 'Food & Lifestyle'), ('tech_gaming', 'Tech & Gaming'), ('fitness_health', 'Fitness & Health'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('business_finance', 'Business & Finance'), ('other', 'Other')], max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('address', models.TextField(blank=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('aadhar_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=11)),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'influencer_profiles',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest')], max_length=20)),
                ('handle', models.CharField(max_length=100)),
                ('profile_url', models.URLField(blank=True)),
                ('followers_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('following_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('posts_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('engagement_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('average_likes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_comments', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_shares', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='influencers.influencerprofile')),
            ],
            options={
                'db_table': 'social_media_accounts',
                'indexes': [models.Index(fields=['platform'], name='social_medi_platfor_673f7d_idx'), models.Index(fields=['followers_count'], name='social_medi_followe_025482_idx'), models.Index(fields=['engagement_rate'], name='social_medi_engagem_5c67a3_idx'), models.Index(fields=['is_active'], name='social_medi_is_acti_490de0_idx')],
                'unique_together': {('influencer', 'platform', 'handle')},
            },
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['username'], name='influencer__usernam_7babe3_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['industry'], name='influencer__industr_eadff7_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['is_verified'], name='influencer__is_veri_bb7c21_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['created_at'], name='influencer__created_ea7231_idx'),
        ),
    ]
