# Generated by Django 4.2.16 on 2025-08-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='country_code',
            field=models.CharField(default='+91', help_text='Country code for phone number (e.g., +1, +44, +91)', max_length=5),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
