# Generated by Django 4.2.16 on 2025-09-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='collaboration_types',
            field=models.JSONField(blank=True, default=list, help_text='Preferred collaboration types (list of choices: cash, barter, hybrid)', null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='minimum_collaboration_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum amount required for cash collaborations', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='industry',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('fashion_beauty', 'Fashion & Beauty'), ('food_lifestyle', 'Food & Lifestyle'), ('tech_gaming', 'Tech & Gaming'), ('fitness_health', 'Fitness & Health'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('business_finance', 'Business & Finance'), ('other', 'Other')], max_length=50),
        ),
    ]
