# Generated by Django 4.2.16 on 2025-08-20 18:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('influencers', '0002_influencerprofile_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='phone_number_verified',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('fashion', 'Fashion'), ('beauty', 'Beauty'), ('fitness', 'Fitness'), ('health', 'Health'), ('food', 'Food'), ('cooking', 'Cooking'), ('travel', 'Travel'), ('lifestyle', 'Lifestyle'), ('tech', 'Technology'), ('gaming', 'Gaming'), ('music', 'Music'), ('dance', 'Dance'), ('comedy', 'Comedy'), ('education', 'Education'), ('business', 'Business'), ('finance', 'Finance'), ('parenting', 'Parenting'), ('pets', 'Pets'), ('sports', 'Sports'), ('art', 'Art'), ('photography', 'Photography'), ('entertainment', 'Entertainment'), ('news', 'News'), ('politics', 'Politics'), ('other', 'Other')], max_length=30), blank=True, default=list, help_text='Content categories the influencer specializes in', null=True, size=None),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
