# Generated by Django 4.2.16 on 2025-10-18 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_countrycode'),
        ('influencers', '0002_influencerprofile_collaboration_types_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='influencerprofile',
            new_name='influencer__industr_bf3beb_idx',
            old_name='influencer__industr_eadff7_idx',
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='influencers', to='common.contentcategory'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='influencers', to='common.industry'),
        ),
    ]
