# Generated by Django 4.2.16 on 2025-10-21 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_rename_influencer__industr_eadff7_idx_influencer__industr_bf3beb_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerprofile',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='engagement_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='followers_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
