# Generated by Django 4.2.16 on 2025-10-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0004_alter_influencerprofile_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='profile_verified',
            field=models.BooleanField(default=False, help_text='Profile is verified when aadhar, email, and phone are all verified'),
        ),
    ]
