# Generated by Django 4.2.16 on 2025-08-21 21:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0004_fix_categories_field_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerAudienceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest')], max_length=20)),
                ('male_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('female_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('other_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('age_18_24_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('age_25_34_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('age_35_44_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('age_45_54_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('age_55_plus_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('top_locations', models.JSONField(default=list)),
                ('top_interests', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('active_followers_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fake_followers_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'influencer_audience_insights',
            },
        ),
        migrations.RemoveIndex(
            model_name='influencerprofile',
            name='influencer__created_ea7231_idx',
        ),
        migrations.RemoveIndex(
            model_name='socialmediaaccount',
            name='social_medi_platfor_673f7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='socialmediaaccount',
            name='social_medi_is_acti_490de0_idx',
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='age_range',
            field=models.CharField(blank=True, choices=[('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55+', '55+')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='audience_age_distribution',
            field=models.JSONField(blank=True, default=dict, help_text='Audience age distribution', null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='audience_gender_distribution',
            field=models.JSONField(blank=True, default=dict, help_text='Audience gender distribution', null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='audience_interests',
            field=models.JSONField(blank=True, default=list, help_text='Audience interests', null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='audience_languages',
            field=models.JSONField(blank=True, default=list, help_text='Audience languages', null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='audience_locations',
            field=models.JSONField(blank=True, default=list, help_text='Top audience locations', null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='barter_ready',
            field=models.BooleanField(default=False, help_text='Ready for barter campaigns'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='bio_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Keywords found in bio', null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='brand_safety_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='campaign_ready',
            field=models.BooleanField(default=False, help_text='Ready for general campaigns'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='collaboration_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='commerce_ready',
            field=models.BooleanField(default=False, help_text='Ready for commerce campaigns'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='contact_availability',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('unavailable', 'Unavailable')], default='available', max_length=50),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='content_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Keywords found in captions and content', null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='content_quality_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='faster_responses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='has_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='has_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='has_linkedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='has_tiktok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='has_twitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='has_youtube',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='influence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Influencer influence score (0-10)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='instagram_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='response_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='average_image_comments',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='average_image_likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='average_reel_comments',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='average_reel_likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='average_reel_plays',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='average_shorts_comments',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='average_shorts_likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='average_shorts_plays',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='average_video_views',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='avg_cpm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average cost per mille (CPM)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='follower_growth_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly follower growth rate (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='last_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='post_performance_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall post performance score (0-10)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='subscriber_growth_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly subscriber growth rate (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='subscribers_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['country'], name='influencer__country_13d506_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['state'], name='influencer__state_261f49_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['city'], name='influencer__city_d57ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['gender'], name='influencer__gender_61285c_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['influence_score'], name='influencer__influen_7f055c_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['commerce_ready'], name='influencer__commerc_dd23db_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['campaign_ready'], name='influencer__campaig_783856_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['barter_ready'], name='influencer__barter__fb4dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['faster_responses'], name='influencer__faster__e64861_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['instagram_verified'], name='influencer__instagr_541266_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['has_instagram'], name='influencer__has_ins_0f4dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['has_youtube'], name='influencer__has_you_7b80bd_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerprofile',
            index=models.Index(fields=['has_tiktok'], name='influencer__has_tik_dd7210_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediaaccount',
            index=models.Index(fields=['influencer', 'platform'], name='social_medi_influen_b3b329_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediaaccount',
            index=models.Index(fields=['platform', 'is_active'], name='social_medi_platfor_16a5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediaaccount',
            index=models.Index(fields=['verified'], name='social_medi_verifie_990a89_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediaaccount',
            index=models.Index(fields=['last_posted_at'], name='social_medi_last_po_4f6e94_idx'),
        ),
        migrations.AddField(
            model_name='influenceraudienceinsight',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_insights', to='influencers.influencerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='influenceraudienceinsight',
            unique_together={('influencer', 'platform')},
        ),
    ]
