# Generated by Django 4.2.16 on 2025-11-12 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0005_influencerprofile_profile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='average_image_comments',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='average_image_likes',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='average_reel_comments',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='average_reel_likes',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='average_reel_plays',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='average_shorts_comments',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='average_shorts_likes',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='average_shorts_plays',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='page_followers',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='page_likes',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='subscribers_count',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='tiktok_followers',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='tiktok_following',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='tiktok_likes',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='tiktok_videos',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='tweets_count',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='twitter_followers',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='twitter_following',
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='average_video_comments',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='average_video_likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='engagement_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Cached engagement metrics computed from recent posts'),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When this account was last synced from scraper', null=True),
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest')], max_length=20)),
                ('platform_post_id', models.CharField(max_length=128)),
                ('post_url', models.URLField(blank=True)),
                ('post_type', models.CharField(blank=True, max_length=50)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('likes_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('comments_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('views_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('shares_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_fetched_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='influencers.socialmediaaccount')),
            ],
            options={
                'db_table': 'social_media_posts',
                'indexes': [models.Index(fields=['account', 'posted_at'], name='social_medi_account_074e03_idx'), models.Index(fields=['platform', 'posted_at'], name='social_medi_platfor_4d994a_idx')],
                'unique_together': {('account', 'platform_post_id')},
            },
        ),
    ]
