# Generated by Django 4.2.16 on 2025-11-14 22:10

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0006_remove_socialmediaaccount_average_image_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerprofile',
            name='aadhar_document',
            field=models.FileField(blank=True, null=True, storage=backend.storage_backends.LocalPrivateMediaStorage(), upload_to=backend.storage_backends.PrivateUploadPath('documents')),
        ),
    ]
