# Generated by Django 4.2.16 on 2025-08-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('influencers', '0006_influencerprofile_available_platforms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerprofile',
            name='categories',
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Content categories the influencer specializes in', related_name='influencers', to='common.category'),
        ),
    ]
