# Generated by Django 4.2.16 on 2025-11-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0007_alter_influencerprofile_aadhar_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='platform_handle',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='platform_profile_link',
        ),
    ]
