# Generated by Django 4.2.16 on 2025-11-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('influencers', '0008_remove_socialmediaaccount_platform_handle_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='influencerprofile',
            name='influencer__instagr_541266_idx',
        ),
        migrations.RemoveIndex(
            model_name='influencerprofile',
            name='influencer__has_ins_0f4dd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='influencerprofile',
            name='influencer__has_you_7b80bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='influencerprofile',
            name='influencer__has_tik_dd7210_idx',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='has_facebook',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='has_instagram',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='has_linkedin',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='has_tiktok',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='has_twitter',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='has_youtube',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='instagram_verified',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='avg_cpm',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='post_performance_score',
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Bio/description from the social platform'),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Display name on the social platform',
                                   max_length=150),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='external_url',
            field=models.URLField(blank=True, help_text='External URL / link in bio set on the platform'),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Whether the account is private on the platform'),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='platform_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Profile image URL from the platform (may expire)'),
        ),
    ]
