# Generated by Django 4.2.16 on 2025-11-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('influencers', '0009_remove_influencerprofile_influencer__instagr_541266_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='profile_image_url',
            field=models.TextField(blank=True, default='',
                                   help_text='Profile image URL from the platform (may expire)'),
        ),
    ]
