# Generated by Django 4.2.16 on 2025-11-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0010_alter_socialmediaaccount_profile_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retry'), ('REVOKED', 'Revoked')], default='PENDING', max_length=50)),
                ('result', models.JSONField(blank=True, default=dict, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'celery_tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_id'], name='celery_task_task_id_f72492_idx'), models.Index(fields=['status'], name='celery_task_status_1c852d_idx'), models.Index(fields=['task_name'], name='celery_task_task_na_18b476_idx'), models.Index(fields=['created_at'], name='celery_task_created_914bf3_idx')],
            },
        ),
    ]
