# Generated by Django 4.2.16 on 2025-11-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0011_celerytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='profile_image_base64',
            field=models.TextField(blank=True, default='', help_text='Profile image as base64 string from scraper API'),
        ),
    ]
