# Generated by Django 4.2.16 on 2025-11-30 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0012_socialmediaaccount_profile_image_base64'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='influencerprofile',
            name='influencer__usernam_7babe3_idx',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='username',
        ),
    ]
