# Generated by Django 4.2.16 on 2025-11-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0013_remove_influencerprofile_influencer__usernam_7babe3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='address_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
