# Generated by Django 4.2.16 on 2025-12-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0014_influencerprofile_address_line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediapost',
            name='raw_data',
        ),
    ]
