# Generated by Django 4.2.16 on 2025-12-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0015_remove_socialmediapost_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='media_urls',
            field=models.JSONField(blank=True, default=list, help_text='Array of media URLs from the scraper API'),
        ),
    ]
