# Generated by Django 4.2.16 on 2025-12-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0016_socialmediapost_media_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='external_url',
            field=models.TextField(blank=True, default='', help_text='External URL / link in bio set on the platform'),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='profile_url',
            field=models.TextField(blank=True, default='', help_text='Profile URL on the social platform'),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='post_url',
            field=models.TextField(blank=True, default='', help_text='URL to the post on the social platform'),
        ),
    ]
