# Generated by Django 4.2.16 on 2025-12-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0017_alter_socialmediaaccount_external_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='profile_image_base64',
        ),
    ]
