# Generated by Django 4.2.16 on 2025-12-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0018_remove_socialmediaaccount_profile_image_base64'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeleryTask',
        ),
    ]
