# Generated by Django 4.2.16 on 2026-01-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_celerytask_crontabscheduleproxy_and_more'),
        ('influencers', '0019_delete_celerytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='verification_rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for rejection (visible to user in profile verification system)'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='influencers', to='common.industry'),
        ),
    ]
