# Generated by Django 4.2.16 on 2026-01-03 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_celerytask_crontabscheduleproxy_and_more'),
        ('influencers', '0019_delete_celerytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerprofile',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='influencers', to='common.industry'),
        ),
    ]
