# Generated by Django 4.2.16 on 2025-09-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the content category')),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI display', max_length=50)),
                ('color', models.CharField(default='blue', help_text='Color theme for UI display', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for display in UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Category',
                'verbose_name_plural': 'Content Categories',
                'db_table': 'content_categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['key'], name='content_cat_key_75d38c_idx'), models.Index(fields=['is_active'], name='content_cat_is_acti_8f8039_idx'), models.Index(fields=['sort_order'], name='content_cat_sort_or_bcc945_idx')],
            },
        ),
    ]
