# Generated by Django 4.2.16 on 2025-10-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_contentcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Country code (e.g., +1, +44)', max_length=10, unique=True)),
                ('country', models.CharField(help_text='Country name', max_length=100)),
                ('flag', models.CharField(blank=True, help_text='Country flag emoji', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country Code',
                'verbose_name_plural': 'Country Codes',
                'db_table': 'country_codes',
                'ordering': ['country'],
                'indexes': [models.Index(fields=['code'], name='country_cod_code_05bffd_idx'), models.Index(fields=['is_active'], name='country_cod_is_acti_4a8705_idx')],
            },
        ),
    ]
