# Generated by Django 4.2.16 on 2025-10-19 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_countrycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcategory',
            name='industry',
            field=models.ForeignKey(default=1, help_text='Industry this content category belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='content_categories', to='common.industry'),
            preserve_default=False,
        ),
    ]
