# Generated by Django 4.2.16 on 2025-10-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_contentcategory_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycode',
            name='shorthand',
            field=models.CharField(default='IN', help_text='Location country code (e.g., US, IN, GB)', max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countrycode',
            name='code',
            field=models.CharField(help_text='Phone country code (e.g., +1, +44)', max_length=10, unique=True),
        ),
    ]
