# Generated by Django 4.2.16 on 2025-12-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('common', '0005_countrycode_shorthand_alter_countrycode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retry'), ('REVOKED', 'Revoked')], default='PENDING', max_length=50)),
                ('result', models.JSONField(blank=True, default=dict, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'celery_tasks',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrontabScheduleProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Crontab Schedule',
                'verbose_name_plural': 'Crontab Schedules',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.crontabschedule',),
        ),
        migrations.CreateModel(
            name='IntervalScheduleProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Interval Schedule',
                'verbose_name_plural': 'Interval Schedules',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.intervalschedule',),
        ),
        migrations.CreateModel(
            name='PeriodicTaskProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Periodic Task',
                'verbose_name_plural': 'Periodic Tasks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_celery_beat.periodictask',),
        ),
    ]
