# Generated by Django 4.2.16 on 2025-08-03 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Brand table already exists from core app, so we just need to mark it as managed by brands app
        migrations.RunSQL(
            "-- Brand table already exists, no need to create",
            reverse_sql="-- No reverse operation needed"
        ),
    ]
