# Generated by Django 4.2.16 on 2025-09-03 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('influencers', '0001_initial'),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkedinfluencer',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='influencers.influencerprofile'),
        ),
        migrations.AddIndex(
            model_name='branduser',
            index=models.Index(fields=['brand'], name='brand_users_brand_i_70ba9e_idx'),
        ),
        migrations.AddIndex(
            model_name='branduser',
            index=models.Index(fields=['role'], name='brand_users_role_5ffd11_idx'),
        ),
        migrations.AddIndex(
            model_name='branduser',
            index=models.Index(fields=['is_active'], name='brand_users_is_acti_376e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='brandauditlog',
            index=models.Index(fields=['brand'], name='brand_audit_brand_i_419984_idx'),
        ),
        migrations.AddIndex(
            model_name='brandauditlog',
            index=models.Index(fields=['user'], name='brand_audit_user_id_ffdebe_idx'),
        ),
        migrations.AddIndex(
            model_name='brandauditlog',
            index=models.Index(fields=['action'], name='brand_audit_action_ac980b_idx'),
        ),
        migrations.AddIndex(
            model_name='brandauditlog',
            index=models.Index(fields=['created_at'], name='brand_audit_created_1e5091_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmarkedinfluencer',
            index=models.Index(fields=['brand'], name='bookmarked__brand_i_fe0e80_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmarkedinfluencer',
            index=models.Index(fields=['created_at'], name='bookmarked__created_719d22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmarkedinfluencer',
            unique_together={('brand', 'influencer')},
        ),
    ]
