# Generated by Django 4.2.16 on 2025-09-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='industry',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('fashion_beauty', 'Fashion & Beauty'), ('food_lifestyle', 'Food & Lifestyle'), ('tech_gaming', 'Tech & Gaming'), ('fitness_health', 'Fitness & Health'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('business_finance', 'Business & Finance'), ('other', 'Other')], max_length=50),
        ),
    ]
