# Generated by Django 5.2.5 on 2025-08-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='country_code',
            field=models.CharField(default='+1', max_length=5),
        ),
    ]
