# Generated by Django 4.2.16 on 2025-10-18 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_countrycode'),
        ('brands', '0003_alter_brand_industry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='brand',
            new_name='brands_industr_c70289_idx',
            old_name='brands_industr_2b91ff_idx',
        ),
        migrations.AlterField(
            model_name='brand',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='common.industry'),
        ),
    ]
