# Generated by Django 4.2.16 on 2025-08-19 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('influencers', '0002_influencerprofile_country_code_and_more'),
        ('brands', '0003_brand_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkedInfluencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bookmarked_influencers',
            },
        ),
        migrations.CreateModel(
            name='BrandAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_invited', 'User Invited'), ('user_role_changed', 'User Role Changed'), ('campaign_created', 'Campaign Created'), ('campaign_updated', 'Campaign Updated'), ('deal_created', 'Deal Created'), ('deal_accepted', 'Deal Accepted'), ('deal_rejected', 'Deal Rejected'), ('content_approved', 'Content Approved'), ('content_rejected', 'Content Rejected'), ('message_sent', 'Message Sent'), ('influencer_bookmarked', 'Influencer Bookmarked')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brand_audit_logs',
            },
        ),
        migrations.CreateModel(
            name='BrandUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Brand Owner'), ('admin', 'Administrator'), ('manager', 'Campaign Manager'), ('editor', 'Content Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'brand_users',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='domain',
            field=models.CharField(default='example.com', help_text='Company domain (e.g., google.com)', max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['domain'], name='brands_domain_aabf2f_idx'),
        ),
        migrations.AddField(
            model_name='branduser',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_users', to='brands.brand'),
        ),
        migrations.AddField(
            model_name='branduser',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brandauditlog',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='brands.brand'),
        ),
        migrations.AddField(
            model_name='brandauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmarkedinfluencer',
            name='bookmarked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmarkedinfluencer',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_influencers', to='brands.brand'),
        ),
        migrations.AddField(
            model_name='bookmarkedinfluencer',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='influencers.influencerprofile'),
        ),
        migrations.AddIndex(
            model_name='branduser',
            index=models.Index(fields=['brand'], name='brand_users_brand_i_70ba9e_idx'),
        ),
        migrations.AddIndex(
            model_name='branduser',
            index=models.Index(fields=['role'], name='brand_users_role_5ffd11_idx'),
        ),
        migrations.AddIndex(
            model_name='branduser',
            index=models.Index(fields=['is_active'], name='brand_users_is_acti_376e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='brandauditlog',
            index=models.Index(fields=['brand'], name='brand_audit_brand_i_419984_idx'),
        ),
        migrations.AddIndex(
            model_name='brandauditlog',
            index=models.Index(fields=['user'], name='brand_audit_user_id_ffdebe_idx'),
        ),
        migrations.AddIndex(
            model_name='brandauditlog',
            index=models.Index(fields=['action'], name='brand_audit_action_ac980b_idx'),
        ),
        migrations.AddIndex(
            model_name='brandauditlog',
            index=models.Index(fields=['created_at'], name='brand_audit_created_1e5091_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmarkedinfluencer',
            index=models.Index(fields=['brand'], name='bookmarked__brand_i_fe0e80_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmarkedinfluencer',
            index=models.Index(fields=['created_at'], name='bookmarked__created_719d22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmarkedinfluencer',
            unique_together={('brand', 'influencer')},
        ),
    ]
