# Generated by Django 4.2.16 on 2025-08-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('brands', '0004_bookmarkedinfluencer_brandauditlog_branduser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='address',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='country_code',
        ),
        migrations.AddField(
            model_name='branduser',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_user_profile', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
