# Generated by Django 4.2.16 on 2025-10-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_rename_brands_industr_2b91ff_idx_brands_industr_c70289_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Lock account for non-payment or other reasons'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_locked'], name='brands_is_lock_8b44fc_idx'),
        ),
    ]
