# Generated by Django 4.2.16 on 2025-11-14 22:08

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_brand_is_locked_brand_brands_is_lock_8b44fc_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='gstin',
            field=models.CharField(blank=True, default='', help_text='Optional GSTIN number used for business verification', max_length=15),
        ),
        migrations.AddField(
            model_name='brand',
            name='verification_document',
            field=models.FileField(blank=True, help_text='Supporting document for manual verification (PAN, Aadhaar, etc.)', null=True, storage=backend.storage_backends.LocalPrivateMediaStorage(), upload_to=backend.storage_backends.brand_verification_upload_to),
        ),
        migrations.AddField(
            model_name='brand',
            name='verification_document_original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='verification_document_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=backend.storage_backends.LocalPublicMediaStorage(), upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='brandauditlog',
            name='action',
            field=models.CharField(choices=[('user_invited', 'User Invited'), ('user_role_changed', 'User Role Changed'), ('user_removed', 'User Removed'), ('brand_updated', 'Brand Updated'), ('campaign_created', 'Campaign Created'), ('campaign_updated', 'Campaign Updated'), ('deal_created', 'Deal Created'), ('deal_accepted', 'Deal Accepted'), ('deal_rejected', 'Deal Rejected'), ('content_approved', 'Content Approved'), ('content_rejected', 'Content Rejected'), ('message_sent', 'Message Sent'), ('influencer_bookmarked', 'Influencer Bookmarked'), ('verification_document_uploaded', 'Verification Document Uploaded')], max_length=50),
        ),
    ]
