# Generated by Django 4.2.16 on 2025-08-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_remove_brand_address_remove_brand_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandauditlog',
            name='action',
            field=models.CharField(choices=[('user_invited', 'User Invited'), ('user_role_changed', 'User Role Changed'), ('user_removed', 'User Removed'), ('brand_updated', 'Brand Updated'), ('campaign_created', 'Campaign Created'), ('campaign_updated', 'Campaign Updated'), ('deal_created', 'Deal Created'), ('deal_accepted', 'Deal Accepted'), ('deal_rejected', 'Deal Rejected'), ('content_approved', 'Content Approved'), ('content_rejected', 'Content Rejected'), ('message_sent', 'Message Sent'), ('influencer_bookmarked', 'Influencer Bookmarked')], max_length=50),
        ),
    ]
