# Generated by Django 4.2.16 on 2025-11-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_brand_gstin_brand_verification_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='whatsapp_credits',
            field=models.IntegerField(default=100, help_text='WhatsApp message credits available for this brand'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['whatsapp_credits'], name='brands_whatsap_f46275_idx'),
        ),
    ]
