# Generated by Django 4.2.16 on 2025-12-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_brand_whatsapp_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='website',
            field=models.TextField(blank=True, default='', help_text='Brand website URL'),
        ),
    ]
