# Generated by Django 4.2.16 on 2025-11-14 22:10

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, storage=backend.storage_backends.LocalPrivateMediaStorage(), upload_to=backend.storage_backends.PrivateUploadPath('message_attachments')),
        ),
    ]
