# Generated by Django 4.2.16 on 2025-11-14 22:10

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=backend.storage_backends.LocalPublicMediaStorage(), upload_to='profiles/'),
        ),
    ]
