# Generated by Django 4.2.16 on 2025-12-01 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_remove_userprofile_user_profil_country_62f4a9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTapLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('use_count', models.IntegerField(default=0, help_text='Number of times this token has been used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_tap_login_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'one_tap_login_tokens',
                'indexes': [models.Index(fields=['token_hash'], name='one_tap_log_token_h_b97cf7_idx'), models.Index(fields=['user'], name='one_tap_log_user_id_afb446_idx'), models.Index(fields=['expires_at'], name='one_tap_log_expires_ff551b_idx')],
            },
        ),
    ]
