import { DashboardStats, Deal, Notification, Message } from "@/types";

export const mockDashboardStats: DashboardStats = {
  total_invitations: 24,
  active_deals: 3,
  completed_deals: 18,
  total_earnings: 125000,
  pending_payments: 15000,
  this_month_earnings: 25000,
  collaboration_rate: 75.0,
  average_deal_value: 6944,
};

export const mockDeals: Deal[] = [
  {
    id: 1,
    campaign: {
      id: 1,
      brand: {
        id: 1,
        name: "Fashion Forward",
        logo: "https://via.placeholder.com/40x40?text=FF",
        description: "Premium fashion brand",
        website: "https://fashionforward.com",
        rating: 4.5,
        total_collaborations: 150,
      },
      title: "Summer Collection Launch",
      description: "Promote our new summer collection with authentic lifestyle content showcasing versatile pieces for young professionals.",
      deal_type: "hybrid" as const,
      cash_amount: 15000,
      product_value: 8000,
      content_requirements: {
        platforms: ["Instagram", "YouTube"],
        content_types: ["Post", "Story", "Reel"],
        post_count: 3,
        story_count: 5,
        reel_count: 1,
        special_instructions: "Include brand hashtag and tag @fashionforward",
      },
      application_deadline: "2025-02-15T23:59:59Z",
      campaign_start_date: "2025-02-20T00:00:00Z",
      campaign_end_date: "2025-03-20T23:59:59Z",
      created_at: "2025-01-20T10:00:00Z",
    },
    influencer: 1,
    status: "invited" as const,
    invited_at: "2025-01-25T14:30:00Z",
    total_value: 23000,
    payment_status: "pending" as const,
  },
  {
    id: 2,
    campaign: {
      id: 2,
      brand: {
        id: 2,
        name: "TechGear Pro",
        logo: "https://via.placeholder.com/40x40?text=TG",
        description: "Professional tech accessories",
        website: "https://techgearpro.com",
        rating: 4.8,
        total_collaborations: 200,
      },
      title: "Wireless Headphones Review",
      description: "Create an honest review of our latest wireless headphones focusing on sound quality and comfort for content creators.",
      deal_type: "barter" as const,
      cash_amount: 0,
      product_value: 12000,
      content_requirements: {
        platforms: ["YouTube", "Instagram"],
        content_types: ["Video", "Post"],
        post_count: 2,
        special_instructions: "Include unboxing and detailed review",
      },
      application_deadline: "2025-02-10T23:59:59Z",
      campaign_start_date: "2025-02-15T00:00:00Z",
      campaign_end_date: "2025-03-15T23:59:59Z",
      created_at: "2025-01-22T09:00:00Z",
    },
    influencer: 1,
    status: "active" as const,
    invited_at: "2025-01-24T11:15:00Z",
    responded_at: "2025-01-24T16:30:00Z",
    total_value: 12000,
    payment_status: "pending" as const,
  },
  {
    id: 3,
    campaign: {
      id: 3,
      brand: {
        id: 3,
        name: "Wellness Co",
        logo: "https://via.placeholder.com/40x40?text=WC",
        description: "Natural wellness products",
        website: "https://wellnessco.com",
        rating: 4.2,
        total_collaborations: 80,
      },
      title: "Skincare Routine Challenge",
      description: "30-day skincare routine challenge featuring our organic skincare line with daily progress updates.",
      deal_type: "paid" as const,
      cash_amount: 20000,
      product_value: 5000,
      content_requirements: {
        platforms: ["Instagram", "TikTok"],
        content_types: ["Story", "Reel", "Post"],
        post_count: 4,
        story_count: 30,
        reel_count: 3,
        special_instructions: "Daily story updates for 30 days",
      },
      application_deadline: "2025-02-05T23:59:59Z",
      campaign_start_date: "2025-02-10T00:00:00Z",
      campaign_end_date: "2025-03-12T23:59:59Z",
      created_at: "2025-01-18T15:00:00Z",
    },
    influencer: 1,
    status: "invited" as const,
    invited_at: "2025-01-23T09:45:00Z",
    total_value: 25000,
    payment_status: "pending" as const,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 1,
    type: "deal_invitation",
    title: "New Deal Invitation",
    message: "Fashion Forward has invited you to collaborate on their Summer Collection Launch campaign.",
    read: false,
    created_at: "2025-01-25T14:30:00Z",
    action_url: "/deals/1",
  },
  {
    id: 2,
    type: "deal_update",
    title: "Deal Status Updated",
    message: "Your collaboration with TechGear Pro has been approved and is now active.",
    read: false,
    created_at: "2025-01-24T16:30:00Z",
    action_url: "/deals/2",
  },
  {
    id: 3,
    type: "message",
    title: "New Message",
    message: "Wellness Co sent you a message regarding the Skincare Routine Challenge.",
    read: true,
    created_at: "2025-01-23T12:15:00Z",
    action_url: "/messages/3",
  },
  {
    id: 4,
    type: "payment",
    title: "Payment Processed",
    message: "Your payment of ₹18,000 from Beauty Brand has been processed successfully.",
    read: true,
    created_at: "2025-01-22T10:00:00Z",
  },
  {
    id: 5,
    type: "system",
    title: "Profile Verification",
    message: "Your profile verification documents have been approved.",
    read: true,
    created_at: "2025-01-20T14:00:00Z",
    action_url: "/profile",
  },
];

export const mockMessages: Record<number, Message[]> = {
  1: [
    {
      id: 1,
      conversation: 1,
      sender: "brand",
      message: "Hi! Thank you for your interest in our Summer Collection Launch campaign. We're excited to potentially work with you!",
      sent_at: "2025-01-25T15:00:00Z",
      read_at: "2025-01-25T15:05:00Z",
    },
    {
      id: 2,
      conversation: 1,
      sender: "influencer",
      message: "Hello! I'm really excited about this opportunity. The summer collection looks amazing. I have a few questions about the content requirements.",
      sent_at: "2025-01-25T15:30:00Z",
      read_at: "2025-01-25T15:32:00Z",
    },
    {
      id: 3,
      conversation: 1,
      sender: "brand",
      message: "Of course! Feel free to ask any questions. We want to make sure you have all the information you need.",
      sent_at: "2025-01-25T16:00:00Z",
      read_at: "2025-01-25T16:02:00Z",
    },
    {
      id: 4,
      conversation: 1,
      sender: "influencer",
      message: "Great! For the Instagram posts, do you have specific styling preferences? And should I include any particular hashtags beyond the brand tag?",
      sent_at: "2025-01-25T16:15:00Z",
      read_at: "2025-01-25T16:20:00Z",
    },
    {
      id: 5,
      conversation: 1,
      sender: "brand",
      message: "For styling, we love authentic, lifestyle-focused content. Think casual elegance - pieces that work for both work and weekend. As for hashtags, please use #FashionForwardSummer and #SummerVibes along with @fashionforward",
      sent_at: "2025-01-25T17:00:00Z",
      read_at: "2025-01-25T17:05:00Z",
    },
    {
      id: 6,
      conversation: 1,
      sender: "brand",
      message: "I'm also attaching our brand guidelines document for your reference.",
      file_url: "https://example.com/brand-guidelines.pdf",
      file_name: "Fashion_Forward_Brand_Guidelines.pdf",
      sent_at: "2025-01-25T17:01:00Z",
      read_at: "2025-01-25T17:06:00Z",
    },
  ],
  2: [
    {
      id: 7,
      conversation: 2,
      sender: "brand",
      message: "Welcome to the TechGear Pro family! We're thrilled to have you review our latest wireless headphones.",
      sent_at: "2025-01-24T17:00:00Z",
      read_at: "2025-01-24T17:10:00Z",
    },
    {
      id: 8,
      conversation: 2,
      sender: "influencer",
      message: "Thank you! I'm excited to try them out. When can I expect the headphones to arrive?",
      sent_at: "2025-01-24T18:00:00Z",
      read_at: "2025-01-24T18:05:00Z",
    },
    {
      id: 9,
      conversation: 2,
      sender: "brand",
      message: "They should arrive within 2-3 business days. I'll send you the tracking information once they're shipped. The package will include the headphones, charging case, and some promotional materials.",
      sent_at: "2025-01-24T18:30:00Z",
      read_at: "2025-01-24T18:35:00Z",
    },
    {
      id: 10,
      conversation: 2,
      sender: "brand",
      message: "Here's a product image for your reference while you wait!",
      file_url: "https://via.placeholder.com/400x300?text=TechGear+Headphones",
      file_name: "techgear_headphones_promo.jpg",
      sent_at: "2025-01-24T18:31:00Z",
      read_at: "2025-01-24T18:36:00Z",
    },
    {
      id: 11,
      conversation: 2,
      sender: "influencer",
      message: "Perfect! I'll keep an eye out for the package. Should I focus on any particular features in my review?",
      sent_at: "2025-01-24T19:00:00Z",
      read_at: "2025-01-24T19:05:00Z",
    },
    {
      id: 12,
      conversation: 2,
      sender: "brand",
      message: "Great question! We'd love you to highlight the noise cancellation, battery life (up to 30 hours), and comfort for long sessions. The sound quality for both music and calls is also a key selling point.",
      sent_at: "2025-01-24T19:30:00Z",
    },
  ],
  3: [
    {
      id: 13,
      conversation: 3,
      sender: "brand",
      message: "Hi there! We'd love to have you participate in our 30-day skincare routine challenge. Are you interested in learning more?",
      sent_at: "2025-01-23T10:00:00Z",
      read_at: "2025-01-23T12:15:00Z",
    },
    {
      id: 14,
      conversation: 3,
      sender: "influencer",
      message: "Hi! Yes, I'm definitely interested. Could you tell me more about the daily requirements? 30 days of stories sounds like a lot of content!",
      sent_at: "2025-01-23T14:00:00Z",
      read_at: "2025-01-23T14:05:00Z",
    },
    {
      id: 15,
      conversation: 3,
      sender: "brand",
      message: "I understand your concern! The daily stories can be simple - just a quick update on how your skin is feeling, which products you're using that day, or even just a selfie with the products. We want it to feel authentic, not forced.",
      sent_at: "2025-01-23T15:00:00Z",
      read_at: "2025-01-23T15:10:00Z",
    },
    {
      id: 16,
      conversation: 3,
      sender: "brand",
      message: "We'll also provide you with content ideas and templates to make it easier. Plus, you'll get our complete skincare routine worth ₹5,000 to keep!",
      sent_at: "2025-01-23T15:01:00Z",
      read_at: "2025-01-23T15:11:00Z",
    },
  ],
};